### ISSUE TITLE
Interested in contributing to Skopy?

### ISSUE THREAD

**Issue by 0x00b1** [chanzuckerberg/starfish#2]
I have been working on a similar application [Skopy](https://github.com/broadinstitute/skopy). It can be used for feature extraction (i.e. similar to CellProfiler’s measurement modules), but I plan on adding image segmentation and object detection in the near future. It has nearly the same mission, providing a ready-made pipeline for image analysis, but it has a simple, portable, and lightweight architecture and people have already started using it. Would you be interested in contributing? It could be fun!

**Comment by freeman-lab** [comment]
Hey @0x00b1! Thanks so much for sharing, we hadn't seen `skopy`, and it looks like a really cool effort. This package `starfish` is currently pretty focused on prototyping a standard pipeline for image-based transcriptomics analysis, as opposed to a more general image processing / feature extraction / pipeline tool -- consider this a learning exercise to get us started.

We're also super interested in working on or helping to improve those kinds of more general tools. As we start to go in that direction, we'll definitely dig into `skopy` -- as well as all the other tools in this ecosystem, of course! -- and hopefully we can find a way to collaborate.
