### ISSUE TITLE
error running detect_spots

### ISSUE THREAD

**Issue by freeman-lab** [chanzuckerberg/starfish#7]
The `gather` step of `munge.py` is giving a `ValueError: setting an array element with a sequence`.

The error arises during the `pd.melt` in the function below. Haven't tried to chase down further, wanted to flag it.

```
def gather(df, key, value, cols):
    id_vars = [col for col in df.columns if col not in cols]
    id_values = cols
    var_name = key
    value_name = value
    return pd.melt(df, id_vars, id_values, var_name, value_name)
```

**Comment by dganguli** [comment]
what versions of pandas and python are you on? can you report the stack trace? i have't seen this error come up on anyone else's machine yet.

**Comment by freeman-lab** [comment]
tracked it down, must have been the `pandas` version, will close!
